### ISSUE TITLE
Setting deployment marker fails with "invalid entity GUID format"

### ISSUE THREAD

**Issue by bbeesley** [newrelic/newrelic-cli#1606]
### Description

We extensively use the [deployment marker action](https://github.com/newrelic/deployment-marker-action). It has worked perfectly for many months. Since [this PR](https://github.com/newrelic/newrelic-cli/pull/1605) was merged our calls to set the deployment marker now fail every time with a "invalid entity GUID format" error. The guid format isn't invalid, it's the same as its always been and it works fine with the previous version.

### Go Version
Unclear, it comes from [this docker image](https://hub.docker.com/r/newrelic/cli/tags).

### Current behavior
set deployment marker now fail every time with a "invalid entity GUID format" error.

### Expected behavior
set deployment marker properly sets a deployment marker

### Steps To Reproduce
Attempt to set a deployment marker using the github action, eg:

```
    - name: set newrelic application deployment marker
      uses: newrelic/deployment-marker-action@v2.2.0
      with:
        apiKey: NRAK-MYSECRETAPIKEY
        region: US
        guid: NDE2ODXXXXXXXXXXXXXXXXXXXXXXXXXXXX # obviously this should be an actual guid
        version: 69369ec22b883042b8f85d034900d469ae417656
        user: my-bot-user
        deploymenttype: BASIC
```
